package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallCouponUser;
import com.example.tinymall.domain.TinymallCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int insert(TinymallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(TinymallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    TinymallCouponUser selectOneByExample(TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    TinymallCouponUser selectOneByExampleSelective(@Param("example") TinymallCouponUserExample example, @Param("selective") TinymallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    List<TinymallCouponUser> selectByExampleSelective(@Param("example") TinymallCouponUserExample example, @Param("selective") TinymallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    List<TinymallCouponUser> selectByExample(TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    TinymallCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    TinymallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    TinymallCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallCouponUser record, @Param("example") TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallCouponUser record, @Param("example") TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}