package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallSystem;
import com.example.tinymall.domain.TinymallSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    long countByExample(TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int insert(TinymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int insertSelective(TinymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    TinymallSystem selectOneByExample(TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    TinymallSystem selectOneByExampleSelective(@Param("example") TinymallSystemExample example, @Param("selective") TinymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    List<TinymallSystem> selectByExampleSelective(@Param("example") TinymallSystemExample example, @Param("selective") TinymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    List<TinymallSystem> selectByExample(TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    TinymallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    TinymallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    TinymallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallSystem record, @Param("example") TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallSystem record, @Param("example") TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}