package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallCoupon;
import com.example.tinymall.domain.TinymallCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    long countByExample(TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int insert(TinymallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(TinymallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    TinymallCoupon selectOneByExample(TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    TinymallCoupon selectOneByExampleSelective(@Param("example") TinymallCouponExample example, @Param("selective") TinymallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    List<TinymallCoupon> selectByExampleSelective(@Param("example") TinymallCouponExample example, @Param("selective") TinymallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    List<TinymallCoupon> selectByExample(TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    TinymallCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    TinymallCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    TinymallCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallCoupon record, @Param("example") TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallCoupon record, @Param("example") TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}