package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallAd;
import com.example.tinymall.domain.TinymallAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    long countByExample(TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int insert(TinymallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int insertSelective(TinymallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    TinymallAd selectOneByExample(TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    TinymallAd selectOneByExampleSelective(@Param("example") TinymallAdExample example, @Param("selective") TinymallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    List<TinymallAd> selectByExampleSelective(@Param("example") TinymallAdExample example, @Param("selective") TinymallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    List<TinymallAd> selectByExample(TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    TinymallAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    TinymallAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    TinymallAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallAd record, @Param("example") TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallAd record, @Param("example") TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}