package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallGoodsSpecification;
import com.example.tinymall.domain.TinymallGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int insert(TinymallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(TinymallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    TinymallGoodsSpecification selectOneByExample(TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    TinymallGoodsSpecification selectOneByExampleSelective(@Param("example") TinymallGoodsSpecificationExample example, @Param("selective") TinymallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    List<TinymallGoodsSpecification> selectByExampleSelective(@Param("example") TinymallGoodsSpecificationExample example, @Param("selective") TinymallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    List<TinymallGoodsSpecification> selectByExample(TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    TinymallGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    TinymallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    TinymallGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallGoodsSpecification record, @Param("example") TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallGoodsSpecification record, @Param("example") TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}