package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallRole;
import com.example.tinymall.domain.TinymallRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    long countByExample(TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int insert(TinymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int insertSelective(TinymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    TinymallRole selectOneByExample(TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    TinymallRole selectOneByExampleSelective(@Param("example") TinymallRoleExample example, @Param("selective") TinymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    List<TinymallRole> selectByExampleSelective(@Param("example") TinymallRoleExample example, @Param("selective") TinymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    List<TinymallRole> selectByExample(TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    TinymallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    TinymallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    TinymallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallRole record, @Param("example") TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallRole record, @Param("example") TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}