package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallCollect;
import com.example.tinymall.domain.TinymallCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    long countByExample(TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int insert(TinymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int insertSelective(TinymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    TinymallCollect selectOneByExample(TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    TinymallCollect selectOneByExampleSelective(@Param("example") TinymallCollectExample example, @Param("selective") TinymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    List<TinymallCollect> selectByExampleSelective(@Param("example") TinymallCollectExample example, @Param("selective") TinymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    List<TinymallCollect> selectByExample(TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    TinymallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    TinymallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    TinymallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallCollect record, @Param("example") TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallCollect record, @Param("example") TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}