package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallCart;
import com.example.tinymall.domain.TinymallCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    long countByExample(TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int insert(TinymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int insertSelective(TinymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    TinymallCart selectOneByExample(TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    TinymallCart selectOneByExampleSelective(@Param("example") TinymallCartExample example, @Param("selective") TinymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    List<TinymallCart> selectByExampleSelective(@Param("example") TinymallCartExample example, @Param("selective") TinymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    List<TinymallCart> selectByExample(TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    TinymallCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    TinymallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    TinymallCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallCart record, @Param("example") TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallCart record, @Param("example") TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}