package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallGroupon;
import com.example.tinymall.domain.TinymallGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    long countByExample(TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int insert(TinymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(TinymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    TinymallGroupon selectOneByExample(TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    TinymallGroupon selectOneByExampleSelective(@Param("example") TinymallGrouponExample example, @Param("selective") TinymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    List<TinymallGroupon> selectByExampleSelective(@Param("example") TinymallGrouponExample example, @Param("selective") TinymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    List<TinymallGroupon> selectByExample(TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    TinymallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    TinymallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    TinymallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallGroupon record, @Param("example") TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallGroupon record, @Param("example") TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}