package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallGoodsProduct;
import com.example.tinymall.domain.TinymallGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    long countByExample(TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int insert(TinymallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(TinymallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    TinymallGoodsProduct selectOneByExample(TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    TinymallGoodsProduct selectOneByExampleSelective(@Param("example") TinymallGoodsProductExample example, @Param("selective") TinymallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    List<TinymallGoodsProduct> selectByExampleSelective(@Param("example") TinymallGoodsProductExample example, @Param("selective") TinymallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    List<TinymallGoodsProduct> selectByExample(TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    TinymallGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    TinymallGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    TinymallGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallGoodsProduct record, @Param("example") TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallGoodsProduct record, @Param("example") TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}