package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallGoodsAttribute;
import com.example.tinymall.domain.TinymallGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int insert(TinymallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(TinymallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    TinymallGoodsAttribute selectOneByExample(TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    TinymallGoodsAttribute selectOneByExampleSelective(@Param("example") TinymallGoodsAttributeExample example, @Param("selective") TinymallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    List<TinymallGoodsAttribute> selectByExampleSelective(@Param("example") TinymallGoodsAttributeExample example, @Param("selective") TinymallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    List<TinymallGoodsAttribute> selectByExample(TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    TinymallGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    TinymallGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    TinymallGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallGoodsAttribute record, @Param("example") TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallGoodsAttribute record, @Param("example") TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}