package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallAftersale;
import com.example.tinymall.domain.TinymallAftersaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int insert(TinymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(TinymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    TinymallAftersale selectOneByExample(TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    TinymallAftersale selectOneByExampleSelective(@Param("example") TinymallAftersaleExample example, @Param("selective") TinymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    List<TinymallAftersale> selectByExampleSelective(@Param("example") TinymallAftersaleExample example, @Param("selective") TinymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    List<TinymallAftersale> selectByExample(TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    TinymallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    TinymallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    TinymallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallAftersale record, @Param("example") TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallAftersale record, @Param("example") TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}