package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallPermission;
import com.example.tinymall.domain.TinymallPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    long countByExample(TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int insert(TinymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int insertSelective(TinymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    TinymallPermission selectOneByExample(TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    TinymallPermission selectOneByExampleSelective(@Param("example") TinymallPermissionExample example, @Param("selective") TinymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    List<TinymallPermission> selectByExampleSelective(@Param("example") TinymallPermissionExample example, @Param("selective") TinymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    List<TinymallPermission> selectByExample(TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    TinymallPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    TinymallPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    TinymallPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallPermission record, @Param("example") TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallPermission record, @Param("example") TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}