package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallLog;
import com.example.tinymall.domain.TinymallLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    long countByExample(TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int insert(TinymallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int insertSelective(TinymallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    TinymallLog selectOneByExample(TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    TinymallLog selectOneByExampleSelective(@Param("example") TinymallLogExample example, @Param("selective") TinymallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    List<TinymallLog> selectByExampleSelective(@Param("example") TinymallLogExample example, @Param("selective") TinymallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    List<TinymallLog> selectByExample(TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    TinymallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    TinymallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    TinymallLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallLog record, @Param("example") TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallLog record, @Param("example") TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}