package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallKeyword;
import com.example.tinymall.domain.TinymallKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    long countByExample(TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int insert(TinymallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int insertSelective(TinymallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    TinymallKeyword selectOneByExample(TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    TinymallKeyword selectOneByExampleSelective(@Param("example") TinymallKeywordExample example, @Param("selective") TinymallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    List<TinymallKeyword> selectByExampleSelective(@Param("example") TinymallKeywordExample example, @Param("selective") TinymallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    List<TinymallKeyword> selectByExample(TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    TinymallKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    TinymallKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    TinymallKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallKeyword record, @Param("example") TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallKeyword record, @Param("example") TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}