package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallNotice;
import com.example.tinymall.domain.TinymallNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    long countByExample(TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int insert(TinymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int insertSelective(TinymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    TinymallNotice selectOneByExample(TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    TinymallNotice selectOneByExampleSelective(@Param("example") TinymallNoticeExample example, @Param("selective") TinymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    List<TinymallNotice> selectByExampleSelective(@Param("example") TinymallNoticeExample example, @Param("selective") TinymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    List<TinymallNotice> selectByExample(TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    TinymallNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    TinymallNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    TinymallNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallNotice record, @Param("example") TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallNotice record, @Param("example") TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}