package com.example.tinymall.dao;

import com.example.tinymall.domain.TinymallNoticeAdmin;
import com.example.tinymall.domain.TinymallNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TinymallNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int insert(TinymallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(TinymallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    TinymallNoticeAdmin selectOneByExample(TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    TinymallNoticeAdmin selectOneByExampleSelective(@Param("example") TinymallNoticeAdminExample example, @Param("selective") TinymallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    List<TinymallNoticeAdmin> selectByExampleSelective(@Param("example") TinymallNoticeAdminExample example, @Param("selective") TinymallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    List<TinymallNoticeAdmin> selectByExample(TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    TinymallNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TinymallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    TinymallNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    TinymallNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TinymallNoticeAdmin record, @Param("example") TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TinymallNoticeAdmin record, @Param("example") TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TinymallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TinymallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TinymallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}